import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const GeneralSans = localFont({
    src: '../public/fonts/GeneralSans-Variable.ttf',
    display: 'swap',
    variable: '--font-general-sans',
  })

const CabinetGrotesk = localFont({
    src: '../public/fonts/CabinetGrotesk-Variable.ttf',
    display: 'swap',
    variable: '--font-cabinet-grotesk',
  })

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
